apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub-outpost.fullname" . }}
  labels:
    {{- include "jupyterhub-outpost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    {{- include "jupyterhub-outpost.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: http
      name: http
      {{- with .Values.service.ports.nodePort }}
      nodePort: {{ . }}
      {{- end }}
    - port: {{ .Values.service.sshport }}
      targetPort: ssh
      name: ssh
      {{- with .Values.service.ports.sshNodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- with .Values.hub.service.extraPorts }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
