apiVersion: v1
entries:
  jupyterhub-outpost:
  - apiVersion: v2
    appVersion: 0.2.5-dev.5
    created: "2023-10-05T14:36:45.444300914Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 847445acafc28ae63e03569659b762dfc6c91ab952106168183be2e92ed70979
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.5-dev.5.tgz
    version: 0.2.5-dev.5
  - apiVersion: v2
    appVersion: 0.2.5-dev.4
    created: "2023-10-05T14:36:45.443638304Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 6292c3bcc4971e29dc4412f0a7a0c70565578ec41750e6cd1ec950e2e26dd1f1
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.5-dev.4.tgz
    version: 0.2.5-dev.4
  - apiVersion: v2
    appVersion: 0.2.5-dev.3
    created: "2023-10-05T14:36:45.442987009Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: ca4de748dc5e194416371457adbc10412598e32c143dd433c7c9379ab6da3cc7
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.5-dev.3.tgz
    version: 0.2.5-dev.3
  - apiVersion: v2
    appVersion: 0.2.5-dev.2
    created: "2023-10-05T14:36:45.442300184Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: e6690cf270fc9e82a919e121b84a92efcdd8fc10b368d6a4ee92f7fefa5e0513
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.5-dev.2.tgz
    version: 0.2.5-dev.2
  - apiVersion: v2
    appVersion: 0.2.5-dev.1
    created: "2023-10-05T14:36:45.44160977Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 09942cb40f62a2f26f56d9bb09eba85968db9f3db19290b972c5dd753426bece
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.5-dev.1.tgz
    version: 0.2.5-dev.1
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2023-10-05T14:36:45.440739779Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 83f9163585928839547da90ead32cc97d82a5850eedc012a42bfcc5e3dfbf49c
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 0.2.3
    created: "2023-10-05T14:36:45.440001044Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 15231bf52c347886ce3e3fdf59ef930f1e3305c18b30e52e7df4ef3099906fe3
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2023-10-05T14:36:45.438486957Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 8037f89f1bae5ebd209a004e7c5076dfad44e870e788e523adad4790b16dd7bd
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2023-10-05T14:36:45.437544854Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 00a78e32db086069cb17e4badf220fa7177429fa96ec370c4e611887ff0c80fb
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2023-10-05T14:36:45.436389922Z"
    description: Start single-user server via JupyterHub on multiple systems
    digest: 15db511d5fbc6182f9c0d9b19835d817fdc270082cd0d8a4849c9df673c2bd81
    keywords:
    - jupyter
    - jupyterhub
    - python
    - fastapi
    name: jupyterhub-outpost
    sources:
    - https://github.com/kreuzert/jupyterhub-outpost
    type: application
    urls:
    - jupyterhub-outpost-0.2.0.tgz
    version: 0.2.0
generated: "2023-10-05T14:36:45.434105948Z"
